version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: malikalamgirian/devstack:v1
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.15"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: